name = "Simple Hugo"
license = "MIT"
description = "Very simple blogging theme"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo"]
features = ["blog", "themes", "minimal", "responsive"]
min_version = 0.48

[author]
    name = "florianroesler"
    homepage = "https://github.com/florianroesler"
